package com.mujdell2019.hackathon.models;

import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "dellProducts")
public class DellProductDBModel {

	/* Data Members */
	
	private String id;
	private String name;
	private ArrayList<String> locations;
	private int price;
	
	
	/* Constructors */
	
	public DellProductDBModel() {}
	
	public DellProductDBModel(String name, ArrayList<String> locations, int price) {
		this.name = name;
		this.locations = locations;
		this.price = price;
	}
	
	public DellProductDBModel(String id) { this.id = id; }

	
	/* Getters and Setters */
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() { return id; }
	public void setId(String id) { this.id = id; }

	@DynamoDBAttribute(attributeName = "name")
	public String getName() { return name; }
	public void setName(String name) { this.name = name; }

	@DynamoDBAttribute(attributeName = "locations")
	public ArrayList<String> getLocations() { return locations; }
	public void setLocations(ArrayList<String> locations) { this.locations = locations; }

	@DynamoDBAttribute(attributeName = "price")
	public int getPrice() { return price; }
	public void setPrice(int price) { this.price = price; }
}
