package com.mujdell2019.hackathon.models;

import java.sql.Timestamp;
import java.util.ArrayList;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "searchedProducts")
public class SearchedProductDBModel {
	
	/* Data Members */

	private String id;
	private String source;
	private String productId;
	private String name;
	private Timestamp lastSearched;
	private int frequency;
	private int price;
	private ArrayList<String> locations;
	
	
	/* Constructors */
	
	public SearchedProductDBModel() {}
	
	public SearchedProductDBModel(String source, String productId, String name, Timestamp lastSearched, int frequency, int price, ArrayList<String> locations) {
		this.source = source;
		this.productId = productId;
		this.name = name;
		this.lastSearched = lastSearched;
		this.frequency = frequency;
		this.price = price;
		this.locations = locations;
	}
	
	public SearchedProductDBModel(String id) { this.id = id; }
	
	
	/* Getters and Setters */
	
	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	public String getId() { return id; }
	public void setId(String id) { this.id = id; }

	@DynamoDBAttribute(attributeName = "source")
	public String getSource() { return source; }
	public void setSource(String source) { this.source = source; }
	
	@DynamoDBAttribute(attributeName = "productId")
	public String getProductId() { return productId; }
	public void setProductId(String productId) { this.productId = productId; }

	@DynamoDBAttribute(attributeName = "name")
	public String getName() { return name; }
	public void setName(String name) { this.name = name; }

	@DynamoDBAttribute(attributeName = "lastSearched")
	public Timestamp getLastSearched() { return lastSearched; }
	public void setLastSearched(Timestamp lastSearched) { this.lastSearched = lastSearched; }

	@DynamoDBAttribute(attributeName = "frequency")
	public int getFrequency() { return frequency; }
	public void setFrequency(int frequency) { this.frequency = frequency; }

	@DynamoDBAttribute(attributeName = "price")
	public int getPrice() { return price; }
	public void setPrice(int price) { this.price = price; }

	@DynamoDBAttribute(attributeName = "locations")
	public ArrayList<String> getLocations() { return locations; }
	public void setLocations(ArrayList<String> locations) { this.locations = locations; }
}
