# -*- coding: utf-8 -*-
"""Unique.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ocs_EzEMWjgg330gM1gy8N7xU4bMnc6T
"""

import pandas as pd
import numpy as np
# import enumhow to print without line break in python stackoverflow
import math
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
df = pd.read_csv("dell_product_new.csv")
# data.drop(["Team", "Weight"], axis = 1, inplace = True)
df.drop(['image', 'index', 'Discount'], axis=1, inplace=True)
colList = df.columns

for col in colList:
    print(str(col), end = ", ")
    valList = df[col].unique()
    for val in valList:
        print(val, end = ", ")
    print()
# print(df.cpu.unique())

# print(df.gpu.unique())

# print(df.ram_size.unique())

# print(df.storage.unique())

# print(df.display_fps.unique())

# print(df.display_type.unique())

